Implementing PKI - Phase 1 - Fixing scripts.

diff --git a/kafka.yaml b/kafka.yaml
--- a/kafka.yaml
+++ b/kafka.yaml
@@ -135,6 +135,12 @@ write_files:
   path: /root/pki/ca-intermediate.pem
   permissions: '0600'
 
+- encoding: b64
+  content: ${ca_intermediate_key}
+  owner: root:root
+  path: /root/pki/ca-intermediate-key.pem
+  permissions: '0600'
+
 - owner: root:root
   permissions: '0755'
   path: /opt/kafka/tools/enable-authentication.sh
@@ -215,16 +221,13 @@ write_files:
       wget -O /usr/local/bin/cfssljson https://github.com/cloudflare/cfssl/releases/download/v1.6.1/cfssljson_1.6.1_linux_amd64
       chmod +x /usr/local/bin/cfssljson
     fi
-    # Root CA
-    if [ ! -f /root/pki/ca-root.pem ]; then
-      echo "/root/pki/ca-root.pem is required"
-      exit 1
-    fi
-    # Intermediate CA
-    if [ ! -f /root/pki/ca-intermediate.pem ]; then
-      echo "/root/pki/ca-intermediate.pem is required"
-      exit 1
-    fi
+    # Verify CA files
+    for file in "ca-root.pem" "ca-intermediate.pem" "ca-intermediate-key.pem"; do
+      if [ ! -f /root/pki/$file ]; then
+        echo "/root/pki/$file is required"
+        exit 1
+      fi
+    done
     # Generate Server Certificate
     cat <<EOF | cfssl gencert -ca=/root/pki/ca-intermediate.pem -ca-key=/root/pki/ca-intermediate-key.pem - | cfssljson -bare /root/pki/kafka
     {
@@ -254,10 +257,12 @@ write_files:
     EOF
     cat /root/pki/ca-intermediate.pem /root/pki/ca-root.pem > /root/pki/ca-fullchain.pem
     cat /root/pki/kafka.pem /root/pki/ca-fullchain.pem > /root/pki/kafka-fullchain.pem
+    chmod 600 /root/pki/*-fullchain.pem
     # Server Keystore
     TEMP_P12="/tmp/ssl.p12.$(date +%s)"
     TEMP_KEYSTORE="/tmp/ssl.keystore.$(date +%s)"
     TARGET_KEYSTORE="/opt/kafka/config/private.jks"
+    rm -f $TARGET_KEYSTORE
     sudo openssl pkcs12 -export \
       -in /root/pki/kafka-fullchain.pem \
       -inkey /root/pki/kafka-key.pem \
@@ -272,12 +277,11 @@ write_files:
     TEMP_P12="/tmp/ca.p12.$(date +%s)"
     TEMP_TRUSTSTORE="/tmp/ca.keystore.$(date +%s)"
     TARGET_TRUSTSTORE="/opt/kafka/config/truststore.jks"
-    sudo openssl pkcs12 -export \
-      -in /root/pki/ca-fullchain.pem \
-      -out $TEMP_P12 -name ca -password "pass:${jks_passwd}"
-    sudo keytool -importkeystore -alias ca \
-      -deststorepass "${jks_passwd}" -destkeypass "${jks_passwd}" -destkeystore $TEMP_TRUSTTORE \
-      -srckeystore $TEMP_P12 -srcstoretype PKCS12 -srcstorepass "${jks_passwd}"
+    rm -f $TARGET_TRUSTSTORE
+    echo "yes" | sudo keytool -importcert -alias ca-intermediate \
+      -file /root/pki/ca-intermediate.pem -storepass "${jks_passwd}" -keystore $TEMP_TRUSTSTORE
+    echo "yes" | sudo keytool -importcert -alias ca-root \
+      -file /root/pki/ca-root.pem -storepass "${jks_passwd}" -keystore $TEMP_TRUSTSTORE
     sudo cp $TEMP_TRUSTSTORE $TARGET_TRUSTSTORE
     sudo chmod 440 $TARGET_TRUSTSTORE
     sudo rm -f $TEMP_P12 $TEMP_TRUSTSTORE
diff --git a/opennms.yaml b/opennms.yaml
--- a/opennms.yaml
+++ b/opennms.yaml
@@ -112,6 +112,79 @@ write_files:
   path: /root/pki/ca-intermediate.pem
   permissions: '0600'
 
+- encoding: b64
+  content: ${ca_intermediate_key}
+  owner: root:root
+  path: /root/pki/ca-intermediate-key.pem
+  permissions: '0600'
+
+- owner: root:root
+  permissions: '0644'
+  path: /root/nginx-pki.conf
+  content: |
+    # For more information on configuration, see:
+    #   * Official English Documentation: http://nginx.org/en/docs/
+    #   * Official Russian Documentation: http://nginx.org/ru/docs/
+    user nginx;
+    worker_processes auto;
+    error_log /var/log/nginx/error.log;
+    pid /run/nginx.pid;
+    # Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
+    include /usr/share/nginx/modules/*.conf;
+    events {
+      worker_connections 1024;
+    }
+    http {
+      log_format  main  '\$remote_addr - \$remote_user [\$time_local] "\$request" '
+                        '\$status \$body_bytes_sent "\$http_referer" '
+                        '"\$http_user_agent" "\$http_x_forwarded_for"';
+      access_log  /var/log/nginx/access.log  main;
+      sendfile            on;
+      tcp_nopush          on;
+      tcp_nodelay         on;
+      keepalive_timeout   65;
+      types_hash_max_size 2048;
+      include             /etc/nginx/mime.types;
+      default_type        application/octet-stream;
+      # Load modular configuration files from the /etc/nginx/conf.d directory.
+      # See http://nginx.org/en/docs/ngx_core_module.html#include
+      # for more information.
+      include /etc/nginx/conf.d/*.conf;
+      server {
+        server_name  _;
+        root /usr/share/nginx/html;
+        # Load configuration files for the default server block.
+        include /etc/nginx/default.d/*.conf;
+        location / {
+        }
+        error_page 404 /404.html;
+          location = /40x.html {
+        }
+        error_page 500 502 503 504 /50x.html;
+          location = /50x.html {
+        }
+        listen [::]:443 ssl ipv6only=on;
+        listen 443 ssl;
+        ssl_certificate /root/pki/ca-fullchain.pem
+        ssl_certificate_key /root/pki/onms-key.pem
+        ssl_session_cache shared:le_nginx_SSL:10m;
+        ssl_session_timeout 1440m;
+        ssl_session_tickets off;
+        ssl_protocols TLSv1.2 TLSv1.3;
+        ssl_prefer_server_ciphers off;
+        ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";
+      }
+      server {
+        if (\$host = ${full_fqdn}) {
+          return 301 https://\$host\$request_uri;
+        } # managed by Certbot
+        listen       80 default_server;
+        listen       [::]:80 default_server;
+        server_name  _;
+        return 404; # managed by Certbot
+      }
+    }
+
 - owner: root:root
   permissions: '0755'
   path: /opt/opennms/bin/install-security-private.sh
@@ -129,16 +202,13 @@ write_files:
       wget -O /usr/local/bin/cfssljson https://github.com/cloudflare/cfssl/releases/download/v1.6.1/cfssljson_1.6.1_linux_amd64
       chmod +x /usr/local/bin/cfssljson
     fi
-    # Root CA
-    if [ ! -f /root/pki/ca-root.pem ]; then
-      echo "/root/pki/ca-root.pem is required"
-      exit 1
-    fi
-    # Intermediate CA
-    if [ ! -f /root/pki/ca-intermediate.pem ]; then
-      echo "/root/pki/ca-intermediate.pem is required"
-      exit 1
-    fi
+    # Verify CA files
+    for file in "ca-root.pem" "ca-intermediate.pem" "ca-intermediate-key.pem"; do
+      if [ ! -f /root/pki/$file ]; then
+        echo "/root/pki/$file is required"
+        exit 1
+      fi
+    done
     # Generate Server Certificate
     cat <<EOF | cfssl gencert -ca=/root/pki/ca-intermediate.pem -ca-key=/root/pki/ca-intermediate-key.pem - | cfssljson -bare /root/pki/onms
     {
@@ -168,8 +238,9 @@ write_files:
     EOF
     cat /root/pki/ca-intermediate.pem /root/pki/ca-root.pem > /root/pki/ca-fullchain.pem
     cat /root/pki/onms.pem /root/pki/ca-fullchain.pem > /root/pki/onms-fullchain.pem
-    # Configure Nginx
-    # FIXME
+    chmod 600 /root/pki/*-fullchain.pem
+    cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
+    cp /root/nginx-pki.conf /etc/nginx/nginx.conf
 
 - owner: root:root
   permissions: '0755'
