Implementing PKI - Phase 1

diff --git a/kafka.yaml b/kafka.yaml
--- a/kafka.yaml
+++ b/kafka.yaml
@@ -123,9 +123,21 @@ write_files:
     # Recommended to avoid disrupting messages workflow
     delete.topic.enable=false
 
+- encoding: b64
+  content: ${ca_root_pem}
+  owner: root:root
+  path: /root/pki/ca-root.pem
+  permissions: '0600'
+
+- encoding: b64
+  content: ${ca_intermediate_pem}
+  owner: root:root
+  path: /root/pki/ca-intermediate.pem
+  permissions: '0600'
+
 - owner: root:root
   permissions: '0755'
-  path: /tmp/enable-authentication.sh
+  path: /opt/kafka/tools/enable-authentication.sh
   content: |
     #!/bin/bash
     function wait_for {
@@ -188,7 +200,102 @@ write_files:
 
 - owner: root:root
   permissions: '0755'
-  path: /tmp/enable-encryption.sh
+  path: /opt/kafka/tools/enable-encryption-private.sh
+  content: |
+    #!/bin/bash
+    if [ "${security_enabled}" != "true" ]; then
+      echo "Security is not enabled"
+      exit
+    fi
+    if [ ! -f /usr/local/bin/cfssl ]; then
+      wget -O /usr/local/bin/cfssl https://github.com/cloudflare/cfssl/releases/download/v1.6.1/cfssl_1.6.1_linux_amd64
+      chmod +x /usr/local/bin/cfssl
+    fi
+    if [ ! -f /usr/local/bin/cfssljson ]; then
+      wget -O /usr/local/bin/cfssljson https://github.com/cloudflare/cfssl/releases/download/v1.6.1/cfssljson_1.6.1_linux_amd64
+      chmod +x /usr/local/bin/cfssljson
+    fi
+    # Root CA
+    if [ ! -f /root/pki/ca-root.pem ]; then
+      echo "/root/pki/ca-root.pem is required"
+      exit 1
+    fi
+    # Intermediate CA
+    if [ ! -f /root/pki/ca-intermediate.pem ]; then
+      echo "/root/pki/ca-intermediate.pem is required"
+      exit 1
+    fi
+    # Generate Server Certificate
+    cat <<EOF | cfssl gencert -ca=/root/pki/ca-intermediate.pem -ca-key=/root/pki/ca-intermediate-key.pem - | cfssljson -bare /root/pki/kafka
+    {
+      "CN": "${public_fqdn}",
+      "hosts": [
+        "$(hostname)",
+        "${public_fqdn}"
+      ],
+      "key": {
+        "algo": "rsa",
+        "size": 2048
+      },
+      "names": [
+        {
+          "C": "US",
+          "ST": "NC",
+          "O": "The OpenNMS Group, Inc."
+        }
+      ],
+      "expiry": "43800h",
+      "usages": [
+        "signing",
+        "key encipherment",
+        "server auth"
+      ]
+    }
+    EOF
+    cat /root/pki/ca-intermediate.pem /root/pki/ca-root.pem > /root/pki/ca-fullchain.pem
+    cat /root/pki/kafka.pem /root/pki/ca-fullchain.pem > /root/pki/kafka-fullchain.pem
+    # Server Keystore
+    TEMP_P12="/tmp/ssl.p12.$(date +%s)"
+    TEMP_KEYSTORE="/tmp/ssl.keystore.$(date +%s)"
+    TARGET_KEYSTORE="/opt/kafka/config/private.jks"
+    sudo openssl pkcs12 -export \
+      -in /root/pki/kafka-fullchain.pem \
+      -inkey /root/pki/kafka-key.pem \
+      -out $TEMP_P12 -name kafka -password "pass:${jks_passwd}"
+    sudo keytool -importkeystore -alias kafka \
+      -deststorepass "${jks_passwd}" -destkeypass "${jks_passwd}" -destkeystore $TEMP_KEYSTORE \
+      -srckeystore $TEMP_P12 -srcstoretype PKCS12 -srcstorepass "${jks_passwd}"
+    sudo cp $TEMP_KEYSTORE $TARGET_KEYSTORE
+    sudo chmod 440 $TARGET_KEYSTORE
+    sudo rm -f $TEMP_P12 $TEMP_KEYSTORE
+    # Server Truststore
+    TEMP_P12="/tmp/ca.p12.$(date +%s)"
+    TEMP_TRUSTSTORE="/tmp/ca.keystore.$(date +%s)"
+    TARGET_TRUSTSTORE="/opt/kafka/config/truststore.jks"
+    sudo openssl pkcs12 -export \
+      -in /root/pki/ca-fullchain.pem \
+      -out $TEMP_P12 -name ca -password "pass:${jks_passwd}"
+    sudo keytool -importkeystore -alias ca \
+      -deststorepass "${jks_passwd}" -destkeypass "${jks_passwd}" -destkeystore $TEMP_TRUSTTORE \
+      -srckeystore $TEMP_P12 -srcstoretype PKCS12 -srcstorepass "${jks_passwd}"
+    sudo cp $TEMP_TRUSTSTORE $TARGET_TRUSTSTORE
+    sudo chmod 440 $TARGET_TRUSTSTORE
+    sudo rm -f $TEMP_P12 $TEMP_TRUSTSTORE
+    # Update configuration
+    CONFIG="/opt/kafka/config/server.properties"
+    sudo sed -i -r '/listener.security.protocol.map/d' $CONFIG
+    cat <<EOF | sudo tee -a $CONFIG
+    listener.security.protocol.map=INSIDE:SASL_PLAINTEXT,OUTSIDE:SASL_SSL
+    ssl.keystore.location=$TARGET_KEYSTORE
+    ssl.keystore.password=${jks_passwd}
+    ssl.key.password=${jks_passwd}
+    ssl.truststore.location=$TARGET_TRUSTSTORE
+    ssl.truststore.password=${jks_passwd}
+    EOF
+
+- owner: root:root
+  permissions: '0755'
+  path: /opt/kafka/tools/enable-encryption.sh
   content: |
     #!/bin/bash
     if [ "${security_enabled}" != "true" ]; then
@@ -197,6 +304,7 @@ write_files:
     fi
     sudo dnf install -y certbot python3-certbot-nginx
     sudo certbot certonly --standalone -d ${public_fqdn} --non-interactive --agree-tos -m ${email}
+    # Server Keystore
     TEMP_P12="/tmp/ssl.p12.$(date +%s)"
     TEMP_KEYSTORE="/tmp/ssl.keystore.$(date +%s)"
     TARGET_KEYSTORE="/opt/kafka/config/letsencrypt.jks"
@@ -210,6 +318,7 @@ write_files:
     sudo cp $TEMP_KEYSTORE $TARGET_KEYSTORE
     sudo chmod 440 $TARGET_KEYSTORE
     sudo rm -f $TEMP_P12 $TEMP_KEYSTORE
+    # Update configuration
     CONFIG="/opt/kafka/config/server.properties"
     sudo sed -i -r '/listener.security.protocol.map/d' $CONFIG
     cat <<EOF | sudo tee -a $CONFIG
@@ -233,8 +342,9 @@ runcmd:
 - sysctl --system
 - wget -O /tmp/kafka.tar.gz https://downloads.apache.org/kafka/2.8.1/kafka_2.13-2.8.1.tgz
 - cd /opt
-- mkdir kafka
+- mkdir -p kafka
 - tar -xvzf /tmp/kafka.tar.gz -C kafka --strip-components 1
+- rsync -avr /opt/kafka/config/ /opt/kafka/config.bak/
 - mv -f /tmp/*.properties /opt/kafka/config/
 - mkdir -p /data/zookeeper /data/kafka
 - echo 1 > /data/zookeeper/myid
@@ -243,7 +353,7 @@ runcmd:
 - systemctl --now enable kafka
 - systemctl --now enable snmpd
 - systemctl --now enable docker
-- /tmp/enable-authentication.sh
-- /tmp/enable-encryption.sh
+- /opt/kafka/tools/enable-authentication.sh
+- /opt/kafka/tools/enable-encryption.sh
 - usermod -aG docker ${user}
 - docker run --name cmak -d -e ZK_HOSTS="$(hostname):2181" -e KAFKA_MANAGER_AUTH_ENABLED="true" -e KAFKA_MANAGER_USERNAME="${cmak_user}" -e KAFKA_MANAGER_PASSWORD="${cmak_passwd}" -e APPLICATION_SECRET="${cmak_passwd}" -p 9000:9000 hlebalbau/kafka-manager:stable
diff --git a/opennms.yaml b/opennms.yaml
--- a/opennms.yaml
+++ b/opennms.yaml
@@ -100,15 +100,87 @@ write_files:
       proxy_read_timeout  90;
     }
 
+- encoding: b64
+  content: ${ca_root_pem}
+  owner: root:root
+  path: /root/pki/ca-root.pem
+  permissions: '0600'
+
+- encoding: b64
+  content: ${ca_intermediate_pem}
+  owner: root:root
+  path: /root/pki/ca-intermediate.pem
+  permissions: '0600'
+
 - owner: root:root
   permissions: '0755'
-  path: /tmp/enable-security.sh
+  path: /opt/opennms/bin/install-security-private.sh
   content: |
     #!/bin/bash
     if [ "${security_enabled}" != "true" ]; then
       echo "Security is not enabled"
       exit
     fi
+    if [ ! -f /usr/local/bin/cfssl ]; then
+      wget -O /usr/local/bin/cfssl https://github.com/cloudflare/cfssl/releases/download/v1.6.1/cfssl_1.6.1_linux_amd64
+      chmod +x /usr/local/bin/cfssl
+    fi
+    if [ ! -f /usr/local/bin/cfssljson ]; then
+      wget -O /usr/local/bin/cfssljson https://github.com/cloudflare/cfssl/releases/download/v1.6.1/cfssljson_1.6.1_linux_amd64
+      chmod +x /usr/local/bin/cfssljson
+    fi
+    # Root CA
+    if [ ! -f /root/pki/ca-root.pem ]; then
+      echo "/root/pki/ca-root.pem is required"
+      exit 1
+    fi
+    # Intermediate CA
+    if [ ! -f /root/pki/ca-intermediate.pem ]; then
+      echo "/root/pki/ca-intermediate.pem is required"
+      exit 1
+    fi
+    # Generate Server Certificate
+    cat <<EOF | cfssl gencert -ca=/root/pki/ca-intermediate.pem -ca-key=/root/pki/ca-intermediate-key.pem - | cfssljson -bare /root/pki/onms
+    {
+      "CN": "${public_fqdn}",
+      "hosts": [
+        "$(hostname)",
+        "${public_fqdn}"
+      ],
+      "key": {
+        "algo": "rsa",
+        "size": 2048
+      },
+      "names": [
+        {
+          "C": "US",
+          "ST": "NC",
+          "O": "The OpenNMS Group, Inc."
+        }
+      ],
+      "expiry": "43800h",
+      "usages": [
+        "signing",
+        "key encipherment",
+        "server auth"
+      ]
+    }
+    EOF
+    cat /root/pki/ca-intermediate.pem /root/pki/ca-root.pem > /root/pki/ca-fullchain.pem
+    cat /root/pki/onms.pem /root/pki/ca-fullchain.pem > /root/pki/onms-fullchain.pem
+    # Configure Nginx
+    # FIXME
+
+- owner: root:root
+  permissions: '0755'
+  path: /opt/opennms/bin/install-security.sh
+  content: |
+    #!/bin/bash
+    if [ "${security_enabled}" != "true" ]; then
+      echo "Security is not enabled"
+      exit
+    fi
+    # Creating Certificate and configuring TLS in Nginx
     dnf install -y nginx certbot python3-certbot-nginx
     mkdir -p /var/www/${public_fqdn}/.well-known
     chown nginx:nginx /var/www
@@ -116,6 +188,16 @@ write_files:
     systemctl --now enable nginx
     sleep 5
     certbot --nginx -d ${public_fqdn} --non-interactive --agree-tos -m ${email}
+
+- owner: root:root
+  permissions: '0755'
+  path: /opt/opennms/bin/enable-security.sh
+  content: |
+    #!/bin/bash
+    if [ "${security_enabled}" != "true" ]; then
+      echo "Security is not enabled"
+      exit
+    fi
     sed -i -r "s|^;domain =.*|domain = ${public_fqdn}|" /etc/grafana/grafana.ini
     sed -i -r "s|^;root_url =.*|root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/|" /etc/grafana/grafana.ini
     cat <<EOF > /opt/opennms/etc/opennms.properties.d/webui.properties
@@ -195,6 +277,7 @@ runcmd:
 - sed -r -i 's/enabled="false"/enabled="true"/' /opt/opennms/etc/telemetryd-configuration.xml
 - /opt/opennms/bin/runjava -s
 - /opt/opennms/bin/install -dis
-- /tmp/enable-security.sh
+- /opt/opennms/bin/install-security.sh
+- /opt/opennms/bin/enable-security.sh
 - systemctl --now enable opennms
 - systemctl --now enable grafana-server
